const { educationCategories, videos, leaderboard, contactUs, noticeboard, login, register } = require("../controllers/clientControllers");
const router = require("express").Router();
router.get("/education", educationCategories);
router.get("/education/videos", videos);
router.get("/leaderboard", leaderboard);
router.post("/login", login);
router.post("/register", register);
router.post("/contactus", contactUs);
router.get("/noticeboard", noticeboard);
module.exports = router;